# Utiliser une image base python avec FastAPI
FROM python:3.10-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers requirements.txt pour installer les dépendances
COPY backend/requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le contenu dans le répertoire de travail
COPY . .


# Exposer le port 8000 pour l'API
EXPOSE 8000

# Démarrer l'application avec la commande Uvicorn et attendre que MySQL soit prêt
ENTRYPOINT [ -- uvicorn main:app --host 0.0.0.0 --port 8000"]
