# Utiliser une image base python avec FastAPI
FROM python:3.10-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers requirements.txt pour installer les dépendances
COPY backend/requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le contenu dans le répertoire de travail
COPY . .

# Copier le script wait-for-it.sh et lui donner des permissions d'exécution
COPY wait-for-it.sh /app/
RUN chmod +x /app/wait-for-it.sh

# Exposer le port 8000 pour l'API
EXPOSE 8000

# Démarrer l'application avec la commande Uvicorn et attendre que MySQL soit prêt
ENTRYPOINT ["/bin/sh", "-c", "./wait-for-it.sh db:3306 -t 60 -- uvicorn main:app --host 0.0.0.0 --port 8000"]
